site_name: HomePage of CaiYa
site_url: https://j-yi-11.github.io/mymkdocs
site_author: j-yi-11

theme:
  name: material #主题
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
      - navigation.instant   #- header.autohide  #自动隐藏
      - navigation.tracking   #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
      - navigation.tabs   #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
      - navigation.top   # 返回顶部的按钮 在上滑时出现
      - search.suggest   # 搜索输入一些字母时推荐补全整个单词
      - search.highlight   # 搜索出的文章关键词加入高亮
      - navigation.expand   # 打开Tab时左侧目录全部展开
      - search.share   #搜索分享按钮

nav:
  - Home: index.md     # 主页链接
  - Blog:              # 博客链接
    - index: blog/index.md  # 博客主页指向 blog/index.md 文件
  - Develop:
    - Markdown: develop/markdown.md
    - Latex: develop/latex.md
    - Python: develop/python.md
    - C++: develop/c++.md
    - MATLAB: develop/matlab.md
    - Java: develop/java.md
  - Deep Learning:
    - AutoRegressiveModel: deeplearning/Autoregressive model.md
    - StableDiffusion: deeplearning/Diffusion.md
    - Inpainting: deeplearning/Inpainting.md
  - MIT 6.S978:
    - Introduction: MIT-DeepGenerativeModel/Introduction.md
    - Variational Autoencoder: MIT-DeepGenerativeModel/VAE.md
  - Paper Reading:
    - MimicTalk: paper-reading/MimicTalk.md
    - ControlNet: deeplearning/ControlNet.md
  - Interview Questions Picked:
    - IQ Test: interview/iq.md
    - Algorithm: interview/algorithm.md
    
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format # 代码块高亮插件
  - pymdownx.arithmatex:  # latex支持
      generic: true
  - toc:
      permalink: true # 固定标题位置为当前位置
  - pymdownx.highlight: # 代码块高亮
      anchor_linenums: true
      linenums: true # 显示行号
      # auto_title: true # 显示编程语言名称
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "\ue157"


extra_javascript:
  # - javascripts/extra.js  #自定义javascript
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6   #Latex支持
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js   #Latex支持
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - ckplayer/js/ckplayer.js #播放器配置
  - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.min.js  #gitalk支持
  - https://cdn.jsdelivr.net/npm/mermaid@10.0.2/dist/add-html-label-6e56ed67.min.js 
  

extra_css:
  # - stylesheets/extra.css # 自定义CSS
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/link.css  #友链配置
  - https://cdn.jsdelivr.net/npm/gitalk@latest/dist/gitalk.css #gitalk支持
  - ckplayer/css/ckplayer.css   #播放器配置
  - https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.css  # font-awesome表情支持
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css  
  

extra:
  alternate:
    - name: English
      link: https://wcowin-work.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=en&_x_tr_hl=zh-CN&_x_tr_pto=wapp 
      lang: en
    - name: 中国(台湾)
      link: https://wcowin-work.translate.goog/?_x_tr_sl=zh-CN&_x_tr_tl=zh-TW&_x_tr_hl=zh-CN&_x_tr_pto=wapp
      lang: zh-TW
  generator: false  #删除页脚显示“使用 MkDocs 材料制造”
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/j-yi-11
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/2141031639?spm_id_from=333.1007.0.0
    - icon: fontawesome/solid/paper-plane
      link: mailto:<qinfenglanyue@gmail.com>
plugins:
  - search
  - offline
  - git-revision-date-localized:
      type: iso_date
      enable_creation_date: false
      exclude:
        - index.md 
        - blog/*.md
  - blog:
      draft: false
      post_readtime: false
      post_url_format: "{date}/{slug}"
      pagination_url_format: "page/{page}"
      authors_file: "{blog}/.authors.yml"